import type { Component } from 'vue'
import {
  SpeedometerOutline,
  PeopleOutline,
  ShieldCheckmarkOutline,
  RibbonOutline,
  KeyOutline,
  MenuOutline,
  TimeOutline,
  DocumentTextOutline,
  LogInOutline,
  ChatboxEllipsesOutline,
  SettingsOutline,
  CubeOutline,
  GridOutline,
  AppsOutline,
  WarningOutline,
  EyeOutline,
  NotificationsOutline,
  StatsChartOutline,
  BanOutline,
  PhonePortraitOutline,
  FlagOutline,
  PulseOutline,
  LayersOutline,
  ServerOutline,
  AnalyticsOutline,
  TimerOutline,
  CodeSlashOutline,
  MegaphoneOutline,
  StorefrontOutline,
  MailOutline,
  LockClosedOutline,
  ImagesOutline,
  StarOutline,
  CalendarOutline,
  AlertCircleOutline,
  BusinessOutline,
  ClipboardOutline,
  NewspaperOutline,
  FunnelOutline,
  ReorderFourOutline,
} from '@vicons/ionicons5'

const iconMap: Record<string, Component> = {
  Dashboard: SpeedometerOutline,
  People: PeopleOutline,
  Shield: ShieldCheckmarkOutline,
  Badge: RibbonOutline,
  Key: KeyOutline,
  Menu: MenuOutline,
  History: TimeOutline,
  Document: DocumentTextOutline,
  LogIn: LogInOutline,
  Chatbox: ChatboxEllipsesOutline,
  Settings: SettingsOutline,
  Cube: CubeOutline,
  Users: PeopleOutline,
  Message: ChatboxEllipsesOutline,
  Warning: WarningOutline,
  Eye: EyeOutline,
  Bell: NotificationsOutline,
  Notifications: NotificationsOutline,
  Chart: StatsChartOutline,
  Stats: StatsChartOutline,
  Ban: BanOutline,
  Phone: PhonePortraitOutline,
  Devices: PhonePortraitOutline,
  Flag: FlagOutline,
  Pulse: PulseOutline,
  Layers: LayersOutline,
  Server: ServerOutline,
  Analytics: AnalyticsOutline,
  Timer: TimerOutline,
  Code: CodeSlashOutline,
  Megaphone: MegaphoneOutline,
  Storefront: StorefrontOutline,
  Mail: MailOutline,
  LockClosed: LockClosedOutline,
  Images: ImagesOutline,
  Star: StarOutline,
  Calendar: CalendarOutline,
  Layout: ReorderFourOutline,
  ReorderFour: ReorderFourOutline,
  AlertCircle: AlertCircleOutline,
  Business: BusinessOutline,
  Clipboard: ClipboardOutline,
  Newspaper: NewspaperOutline,
  Funnel: FunnelOutline,
  Speedometer: SpeedometerOutline,
}

export function resolveMenuIcon(name?: string): Component {
  if (!name) return AppsOutline
  return iconMap[name] || GridOutline
}
